import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname.replace(/^\/(.:\/)/,'$1')); const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('tar namespace import regression',()=>assert.match(read('electron/services/javaService.js'),/import \* as tar from 'tar'/));
test('renderer has command center',()=>{assert.match(read('src/App.jsx'),/CommandCenter/);assert.match(read('src/components/CommandCenter.jsx'),/Launch/)});
test('no fake random server count',()=>assert.doesNotMatch(read('src/pages/Servers.jsx'),/Math\.random/));
test('offline UUID uses Minecraft OfflinePlayer namespace',()=>assert.match(read('electron/services/accountService.js'),/OfflinePlayer:/));
test('Electron renderer is isolated',()=>{const m=read('electron/main.js');assert.match(m,/contextIsolation:true/);assert.match(m,/nodeIntegration:false/);assert.match(m,/sandbox:true/)});
test('MCLC auth object supports MSA',()=>assert.match(read('electron/services/accountService.js'),/meta:\{type:'msa'/));
test('Fabric profile comes from official metadata endpoint',()=>assert.match(read('electron/services/fabricService.js'),/meta\.fabricmc\.net\/v2/));
test('mod search filters actual MC version and loader',()=>{const m=read('electron/services/modService.js');assert.match(m,/versions:/);assert.match(m,/categories:/)});
test('server ping implements Minecraft handshake',()=>{const m=read('electron/services/serverService.js');assert.match(m,/varInt\(767\)/);assert.match(m,/createConnection/)});
test('logo asset is present',()=>assert.ok(fs.statSync(path.join(root,'assets/logo.svg')).size>1000));
