const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const FALLBACK={version:'v1.1.0',installer:'https://github.com/1x1x1x1x1-Ammar/Eternal-Client/releases/download/v1.1.0/Eternal.Client.Setup.1.1.0.exe',core:'https://github.com/1x1x1x1x1-Ammar/Eternal-Client/releases/download/v1.1.0/Eternal-Core-Standalone-1.1.0.jar'};
function initNav(){const h=$('.site-nav'),b=$('.nav-toggle'),m=$('.mobile-menu');const sync=()=>h?.classList.toggle('scrolled',scrollY>18);sync();addEventListener('scroll',sync,{passive:true});if(!b||!m)return;const close=()=>{m.classList.remove('open');m.setAttribute('aria-hidden','true');b.setAttribute('aria-expanded','false')};b.addEventListener('click',()=>{const open=!m.classList.contains('open');m.classList.toggle('open',open);m.setAttribute('aria-hidden',String(!open));b.setAttribute('aria-expanded',String(open))});$$('a',m).forEach(a=>a.addEventListener('click',close));addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
function initReveal(){const items=$$('.reveal');if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -42px'});items.forEach(i=>io.observe(i))}
function initGlow(){const g=$('.mouse-glow');if(!g||matchMedia('(pointer:coarse)').matches||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let raf=0;addEventListener('pointermove',e=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{g.style.left=e.clientX+'px';g.style.top=e.clientY+'px';g.style.opacity='1'})},{passive:true});addEventListener('pointerleave',()=>g.style.opacity='0')}
function initCopy(){$$('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);const s=$('.copy-state',btn);if(s){s.textContent='✓';setTimeout(()=>s.textContent='▢',1600)}}catch{}}))}
function initClientTabs(){const buttons=$$('[data-client-tab]'),panels=$$('[data-client-panel]');if(!buttons.length)return;const activate=id=>{buttons.forEach(b=>b.classList.toggle('active',b.dataset.clientTab===id));panels.forEach(p=>p.classList.toggle('hidden',p.dataset.clientPanel!==id))};buttons.forEach(b=>b.addEventListener('click',()=>activate(b.dataset.clientTab)))}
function initCarousel(){const wrap=$('[data-carousel]'),track=wrap&&$('.staff-track',wrap),cards=track&&$$('.staff-card',track),prev=wrap&&$('[data-prev]',wrap),next=wrap&&$('[data-next]',wrap);if(!wrap||!track||!cards?.length)return;let idx=0;const update=()=>{if(innerWidth>720){track.style.removeProperty('--staff-offset');return}const cardW=cards[0].getBoundingClientRect().width+12;const max=Math.max(0,cards.length-1);idx=Math.max(0,Math.min(idx,max));track.style.setProperty('--staff-offset',`${-idx*cardW}px`);$$('.carousel-dots span',wrap).forEach((d,i)=>d.classList.toggle('active',i===Math.min(idx,2)))};prev?.addEventListener('click',()=>{idx--;update()});next?.addEventListener('click',()=>{idx++;update()});addEventListener('resize',update,{passive:true});update()}
async function initRelease(){const apply=(version,installer,core)=>{$$('[data-release-version]').forEach(n=>n.textContent=version);['#hero-download','#download-installer'].forEach(s=>$$(s).forEach(a=>a.href=installer));['#core-download'].forEach(s=>$$(s).forEach(a=>a.href=core))};apply(FALLBACK.version,FALLBACK.installer,FALLBACK.core);try{const r=await fetch('https://api.github.com/repos/1x1x1x1x1-Ammar/Eternal-Client/releases/latest',{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)return;const j=await r.json();const exe=j.assets?.find(a=>/Eternal\.Client\.Setup\..*\.exe$/i.test(a.name));const jar=j.assets?.find(a=>/Eternal-Core-Standalone-.*\.jar$/i.test(a.name));apply(j.tag_name||FALLBACK.version,exe?.browser_download_url||FALLBACK.installer,jar?.browser_download_url||FALLBACK.core)}catch{}}
document.addEventListener('DOMContentLoaded',()=>{initNav();initReveal();initGlow();initCopy();initClientTabs();initCarousel();initRelease()});
