import crypto from 'node:crypto';
import { PublicClientApplication } from '@azure/msal-node';
import { store, encryptSecret, decryptSecret } from './store.js';
function offlineUuid(username){const data=Buffer.from(`OfflinePlayer:${username}`,'utf8');const bytes=crypto.createHash('md5').update(data).digest();bytes[6]=(bytes[6]&0x0f)|0x30;bytes[8]=(bytes[8]&0x3f)|0x80;const h=bytes.toString('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
function publicAccount(a){const {secret,...rest}=a;return rest;}
export function listAccounts(){return store.get('accounts').map(publicAccount);} export function activeAccount(){const id=store.get('activeAccountId');return store.get('accounts').find(x=>x.id===id)||null;}
export function addOffline(username){username=String(username||'').trim();if(!/^[A-Za-z0-9_]{3,16}$/.test(username))throw new Error('Offline username must be 3–16 letters, numbers, or underscore.');const account={id:`offline:${offlineUuid(username)}`,type:'offline',username,uuid:offlineUuid(username),createdAt:new Date().toISOString()};const all=store.get('accounts').filter(a=>a.id!==account.id);all.push(account);store.set('accounts',all);store.set('activeAccountId',account.id);return publicAccount(account);}
async function xboxExchange(msToken){const xblRes=await fetch('https://user.auth.xboxlive.com/user/authenticate',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({Properties:{AuthMethod:'RPS',SiteName:'user.auth.xboxlive.com',RpsTicket:`d=${msToken}`},RelyingParty:'http://auth.xboxlive.com',TokenType:'JWT'})});if(!xblRes.ok)throw new Error(`Xbox Live authentication failed (${xblRes.status}).`);const xbl=await xblRes.json();const uhs=xbl.DisplayClaims?.xui?.[0]?.uhs;const xstsRes=await fetch('https://xsts.auth.xboxlive.com/xsts/authorize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({Properties:{SandboxId:'RETAIL',UserTokens:[xbl.Token]},RelyingParty:'rp://api.minecraftservices.com/',TokenType:'JWT'})});if(!xstsRes.ok)throw new Error(`XSTS authentication failed (${xstsRes.status}).`);const xsts=await xstsRes.json();const mcRes=await fetch('https://api.minecraftservices.com/authentication/login_with_xbox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identityToken:`XBL3.0 x=${uhs};${xsts.Token}`})});if(!mcRes.ok)throw new Error(`Minecraft Services login failed (${mcRes.status}).`);const mc=await mcRes.json();const headers={Authorization:`Bearer ${mc.access_token}`};const entRes=await fetch('https://api.minecraftservices.com/entitlements/mcstore',{headers});const ent=await entRes.json();if(!entRes.ok||!Array.isArray(ent.items)||ent.items.length===0)throw new Error('This Microsoft account does not own Minecraft Java Edition.');const profileRes=await fetch('https://api.minecraftservices.com/minecraft/profile',{headers});if(!profileRes.ok)throw new Error('Could not fetch Minecraft profile.');const profile=await profileRes.json();return {mc,profile,xuid:xsts.DisplayClaims?.xui?.[0]?.xid||''};}
export async function loginMicrosoft(deviceCodeCallback){const clientId=store.get('settings.azureClientId')||process.env.ETERNAL_AZURE_CLIENT_ID;if(!clientId)throw new Error('Set your own Microsoft Entra/Azure Client ID in Settings first.');const pca=new PublicClientApplication({auth:{clientId,authority:'https://login.microsoftonline.com/consumers'}});const token=await pca.acquireTokenByDeviceCode({scopes:['XboxLive.signin','offline_access'],deviceCodeCallback});if(!token?.accessToken)throw new Error('Microsoft sign-in did not return an access token.');const {mc,profile,xuid}=await xboxExchange(token.accessToken);const id=`msa:${profile.id}`;const account={id,type:'microsoft',username:profile.name,uuid:profile.id,skinUrl:profile.skins?.[0]?.url||'',createdAt:new Date().toISOString(),secret:encryptSecret({mcAccessToken:mc.access_token,mcExpiresAt:Date.now()+((mc.expires_in||86400)*1000),xuid,clientId})};const all=store.get('accounts').filter(a=>a.id!==id);all.push(account);store.set('accounts',all);store.set('activeAccountId',id);return publicAccount(account);}
export function launcherAuthorization(account){if(!account)throw new Error('Select an account first.');if(account.type==='offline')return {access_token:'',client_token:account.uuid,uuid:account.uuid.replaceAll('-',''),name:account.username,user_properties:'{}',meta:{type:'mojang',demo:false}};const sec=decryptSecret(account.secret);if(!sec?.mcAccessToken)throw new Error('Microsoft session is missing. Sign in again.');if(sec.mcExpiresAt&&sec.mcExpiresAt<Date.now()+60000)throw new Error('Microsoft Minecraft token expired. Sign in again.');return {access_token:sec.mcAccessToken,client_token:account.uuid,uuid:account.uuid,name:account.username,user_properties:'{}',meta:{type:'msa',demo:false,xuid:sec.xuid||'',clientId:sec.clientId||''}};}
export function removeAccount(id){const all=store.get('accounts').filter(a=>a.id!==id);store.set('accounts',all);if(store.get('activeAccountId')===id)store.set('activeAccountId',all[0]?.id||null);return true;} export function activateAccount(id){if(!store.get('accounts').some(a=>a.id===id))throw new Error('Account not found.');store.set('activeAccountId',id);return true;} export {offlineUuid};
