import path from 'node:path';
import { getInstance, instanceDir, patchInstance } from './instanceService.js';
import { installFabricProfile } from './fabricService.js';
import { prepareCore } from './coreService.js';
import { activeAccount, launcherAuthorization } from './accountService.js';
import { store } from './store.js';
import { requiredJavaMajor, detectJava } from './javaService.js';
const processes=new Map();let ClientClass=null;async function clientClass(){if(ClientClass)return ClientClass;const mod=await import('minecraft-launcher-core');ClientClass=mod.Client||mod.default?.Client;if(!ClientClass)throw new Error('minecraft-launcher-core Client export unavailable.');return ClientClass;}
async function resolveJava(inst){const configured=store.get('settings.javaPath');const required=requiredJavaMajor(inst.minecraftVersion);if(configured)return {path:configured,required};const found=await detectJava();const best=found.find(j=>j.major>=required);if(!best)throw new Error(`Minecraft ${inst.minecraftVersion} requires Java ${required}+; configure a compatible Java runtime in Settings.`);return {path:best.path,required};}
export function runningState(){return [...processes.entries()].map(([instanceId,children])=>({instanceId,pids:[...children].map(x=>x.pid),count:children.size}));}
export async function launchInstance({instanceId,server=null,emit=()=>{}}){const inst=await getInstance(instanceId);const gameRoot=path.join(instanceDir(instanceId),'.minecraft');const account=activeAccount();if(!account)throw new Error('Add and select an account before launching.');emit({instanceId,state:'VALIDATING',message:'Validating instance…'});const java=await resolveJava(inst);let versionCustom='';if(inst.loader==='fabric'){emit({instanceId,state:'RESOLVING_LOADER',message:'Resolving Fabric loader…'});const f=await installFabricProfile(gameRoot,inst.minecraftVersion,inst.loaderVersion);versionCustom=f.id;if(inst.minecraftVersion==='1.21.11'){const c=await prepareCore(instanceId);if(!c.installed)emit({instanceId,state:'PREPARING_MODS',message:c.reason,warning:true});}}emit({instanceId,state:'STARTING_JVM',message:'Starting Minecraft…'});const Client=await clientClass();const client=new Client();const settings=store.get('settings');const maxMb=Number(inst.ramMb||settings.ramMb||6144);const customLaunchArgs=[];if(server?.host)customLaunchArgs.push('--quickPlayMultiplayer',`${server.host}:${server.port||25565}`);const opts={authorization:launcherAuthorization(account),root:gameRoot,javaPath:java.path,version:{number:inst.minecraftVersion,type:'release',...(versionCustom?{custom:versionCustom}:{})},memory:{min:`${Math.max(1024,Math.floor(maxMb/2))}M`,max:`${maxMb}M`},window:{width:settings.resolution?.width||1280,height:settings.resolution?.height||720},customLaunchArgs};client.on('progress',p=>emit({instanceId,state:'DOWNLOADING',message:p.type||'Downloading Minecraft files…',progress:p}));client.on('download-status',p=>emit({instanceId,state:'DOWNLOADING',message:'Downloading…',progress:p}));client.on('debug',m=>emit({instanceId,state:'DEBUG',message:String(m)}));client.on('data',m=>emit({instanceId,state:'LOG',message:String(m)}));const child=await client.launch(opts);if(!child?.pid)throw new Error('Minecraft process did not start.');if(!processes.has(instanceId))processes.set(instanceId,new Set());processes.get(instanceId).add(child);const started=Date.now();emit({instanceId,state:'RUNNING',message:`Minecraft running (PID ${child.pid})`,pid:child.pid});await patchInstance(instanceId,{lastPlayedAt:new Date().toISOString()});child.once('close',async code=>{const set=processes.get(instanceId);set?.delete(child);if(set&&set.size===0)processes.delete(instanceId);const latest=await getInstance(instanceId).catch(()=>null);if(latest)await patchInstance(instanceId,{playtimeSeconds:(latest.playtimeSeconds||0)+Math.round((Date.now()-started)/1000)});emit({instanceId,state:'STOPPED',message:`Minecraft exited (${code??'unknown'}).`,code});});return {pid:child.pid};}
export function stopInstance(id){const set=processes.get(id);if(!set?.size)return false;for(const p of set)try{p.kill();}catch{}return true;}
