import fs from 'node:fs/promises';
import path from 'node:path';
import AdmZip from 'adm-zip';
import { getInstance, instanceDir } from './instanceService.js';
import { ensureDir, assertInside } from './fsService.js';
function modsDir(id){return path.join(instanceDir(id),'.minecraft','mods');}
async function metadata(file){const base=path.basename(file);const enabled=!base.endsWith('.disabled');const actual=enabled?base:base.slice(0,-9);let name=actual.replace(/\.jar$/,''),version='',loader='unknown';try{const zip=new AdmZip(file);const entry=zip.getEntry('fabric.mod.json');if(entry){const j=JSON.parse(entry.getData().toString('utf8'));name=j.name||j.id||name;version=j.version||'';loader='fabric';}}catch{}return {filename:base,name,version,loader,enabled,path:file};}
export async function listMods(id){await ensureDir(modsDir(id));const out=[];for(const f of await fs.readdir(modsDir(id)))if(f.endsWith('.jar')||f.endsWith('.jar.disabled'))out.push(await metadata(path.join(modsDir(id),f)));return out;}
export async function addMods(id,files){await getInstance(id);await ensureDir(modsDir(id));const added=[];for(const src of files||[]){if(!String(src).toLowerCase().endsWith('.jar'))continue;const dest=assertInside(modsDir(id),path.join(modsDir(id),path.basename(src)));await fs.copyFile(src,dest);added.push(await metadata(dest));}return added;}
export async function removeMod(id,filename){await fs.rm(assertInside(modsDir(id),path.join(modsDir(id),path.basename(filename))),{force:true});return true;} export async function toggleMod(id,filename,enabled){const src=assertInside(modsDir(id),path.join(modsDir(id),path.basename(filename)));const currently=!src.endsWith('.disabled');if(currently===enabled)return true;await fs.rename(src,enabled?src.replace(/\.disabled$/,''):`${src}.disabled`);return true;}
export async function searchModrinth({query='',mcVersion='',loader='fabric',limit=20}){const facets=[];if(mcVersion)facets.push([`versions:${mcVersion}`]);if(loader)facets.push([`categories:${loader}`]);facets.push(['project_type:mod']);const u=new URL('https://api.modrinth.com/v2/search');u.searchParams.set('query',query);u.searchParams.set('limit',String(Math.min(limit,50)));u.searchParams.set('facets',JSON.stringify(facets));const r=await fetch(u,{headers:{'User-Agent':'EternalClient/0.5.0-beta.5'}});if(!r.ok)throw new Error(`Modrinth search failed (${r.status}).`);return r.json();}
export async function installModrinth({instanceId,projectId}){const inst=await getInstance(instanceId);const u=new URL(`https://api.modrinth.com/v2/project/${encodeURIComponent(projectId)}/version`);u.searchParams.set('game_versions',JSON.stringify([inst.minecraftVersion]));u.searchParams.set('loaders',JSON.stringify([inst.loader]));const r=await fetch(u,{headers:{'User-Agent':'EternalClient/0.5.0-beta.5'}});if(!r.ok)throw new Error(`Modrinth versions failed (${r.status}).`);const versions=await r.json();const v=versions.find(x=>x.version_type==='release')||versions[0];if(!v)throw new Error('No compatible Modrinth version found for this instance.');const file=v.files.find(f=>f.primary)||v.files[0];if(!file)throw new Error('Compatible version has no downloadable file.');await ensureDir(modsDir(instanceId));const dest=path.join(modsDir(instanceId),file.filename);const res=await fetch(file.url,{headers:{'User-Agent':'EternalClient/0.5.0-beta.5'}});if(!res.ok)throw new Error(`Mod download failed (${res.status}).`);await fs.writeFile(dest,Buffer.from(await res.arrayBuffer()));return metadata(dest);}
